- name: Deploy Frontend and Backend Containers
  hosts: aws_servers
  become: yes
  vars:
    docker_registry: "docker.io"
    docker_username: "tasneemkhaled"
    frontend_image_name: "frontend"
    frontend_image_tag: "{{ frontend_image_tag | default('latest') }}"
    backend_image_name: "backend"
    backend_image_tag: "{{ backend_image_tag | default('latest') }}"
    frontend_container_name: "my-frontend-container"
    backend_container_name: "my-backend-container"
    host_frontend_port: 3000
    container_frontend_port: 3000
    host_backend_port: 3001
    container_backend_port: 3001

  tasks:
    - name: Ensure Docker is installed and running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    # Frontend deployment
    - name: Pull frontend Docker image
      community.docker.docker_image:
        name: "{{ docker_registry }}/{{ docker_username }}/{{ frontend_image_name }}:{{ frontend_image_tag }}"
        source: pull

    - name: Stop and remove existing frontend container
      community.docker.docker_container:
        name: "{{ frontend_container_name }}"
        state: absent
        force_kill: yes
      ignore_errors: yes

    - name: Deploy frontend container
      community.docker.docker_container:
        name: "{{ frontend_container_name }}"
        image: "{{ docker_registry }}/{{ docker_username }}/{{ frontend_image_name }}:{{ frontend_image_tag }}"
        ports:
          - "{{ host_frontend_port }}:{{ container_frontend_port }}"
        restart_policy: always
        state: started

    # Backend deployment
    - name: Pull backend Docker image
      community.docker.docker_image:
        name: "{{ docker_registry }}/{{ docker_username }}/{{ backend_image_name }}:{{ backend_image_tag }}"
        source: pull

    - name: Stop and remove existing backend container
      community.docker.docker_container:
        name: "{{ backend_container_name }}"
        state: absent
        force_kill: yes
      ignore_errors: yes

    - name: Deploy backend container
      community.docker.docker_container:
        name: "{{ backend_container_name }}"
        image: "{{ docker_registry }}/{{ docker_username }}/{{ backend_image_name }}:{{ backend_image_tag }}"
        ports:
          - "{{ host_backend_port }}:{{ container_backend_port }}"
        restart_policy: always
        state: started
