---
- name: Deploy Kubernetes Manifests on EC2 Instance
  hosts: kubernetes_hosts
  gather_facts: no

  tasks:
    - name: Apply Kubernetes manifests
      command: "kubectl --kubeconfig=/home/ec2-user/.kube/config apply -f /home/ec2-user/manifests"
      #become: yes
